import type { BuildingPermitResult, ConstructionPlanItem } from './state';

/**
 * Dice/permit-die rolls are carried IN the action (generated by the caller,
 * e.g. the UI), not rolled inside the reducer — keeps the reducer pure and
 * deterministic/testable, same principle as the rest of this codebase.
 */
export type HotelAction =
  | { type: 'ROLL_MOVE_DICE'; value: number }
  | { type: 'BUY_LOT'; lotId: string }
  | { type: 'START_CONSTRUCTION'; plan: ConstructionPlanItem[] }
  | { type: 'ROLL_BUILDING_PERMIT'; value: BuildingPermitResult }
  // A garden-only plan (no buildingCount in any item) doesn't require the
  // risky permit-die roll — resolves immediately at full price, no chance of
  // FREE/DOUBLE/RED. Engine-enforced (canBuildWithoutPermit), not just a UI
  // affordance — rejected outright if the plan includes any building.
  | { type: 'BUILD_WITHOUT_PERMIT'; plan: ConstructionPlanItem[] }
  // No TAKE_FREE_BUILDING — FREE_BUILDING resolves automatically on landing
  // (see reducer.ts's resolveFreeBuilding), there's nothing to choose (a
  // building isn't placed on a specific board space the way a staircase is).
  | { type: 'ROLL_NIGHTS'; value: number }
  | { type: 'BUY_STAIRCASE_RIGHT'; lotId: string; spaceId: string }
  // Landing on FREE_STAIRCASE with somewhere to put it parks the turn in
  // AWAITING_FREE_STAIRCASE_CHOICE instead of auto-picking — the player
  // chooses which of their own lots, and which of ITS available spaces (see
  // docs/hotel-0a-specifikacio.md §9.2). Only auto-resolves (no action needed)
  // when there's genuinely nothing to choose from (no lots, or no room anywhere).
  | { type: 'CHOOSE_FREE_STAIRCASE_SPACE'; lotId: string; spaceId: string }
  | { type: 'START_AUCTION'; lotId: string }
  // During an auction it's NOT the current player acting — any other player
  // can bid, so unlike every other action here (which implicitly targets
  // getCurrentPlayer), these two carry an explicit bidderId.
  | { type: 'PLACE_BID'; bidderId: string; amount: number }
  | { type: 'PASS_BID'; bidderId: string }
  | { type: 'FORFEIT' }
  | { type: 'END_TURN' };
