import type { BuildingPermitResult, ConstructionPlanItem } from './state';

/**
 * Dice/permit-die rolls are carried IN the action (generated by the caller,
 * e.g. the UI), not rolled inside the reducer — keeps the reducer pure and
 * deterministic/testable, same principle as the rest of this codebase.
 */
export type HotelAction =
  | { type: 'ROLL_MOVE_DICE'; value: number }
  | { type: 'BUY_LOT'; lotId: string }
  | { type: 'START_CONSTRUCTION'; plan: ConstructionPlanItem[] }
  | { type: 'ROLL_BUILDING_PERMIT'; value: BuildingPermitResult }
  // No TAKE_FREE_STAIRCASE/TAKE_FREE_BUILDING — FREE_STAIRCASE/FREE_BUILDING
  // spaces resolve automatically on landing (see reducer.ts's
  // resolveFreeStaircase/resolveFreeBuilding), there's nothing to choose.
  | { type: 'ROLL_NIGHTS'; value: number }
  | { type: 'BUY_STAIRCASE_RIGHT'; lotId: string }
  | { type: 'START_AUCTION'; lotId: string }
  // During an auction it's NOT the current player acting — any other player
  // can bid, so unlike every other action here (which implicitly targets
  // getCurrentPlayer), these two carry an explicit bidderId.
  | { type: 'PLACE_BID'; bidderId: string; amount: number }
  | { type: 'PASS_BID'; bidderId: string }
  | { type: 'FORFEIT' }
  | { type: 'END_TURN' };
