// GENERATED FILE — do not hand-edit. Produced by `node scripts/build-gwent-assets.mjs`
// from temp/gwent-card-data.json + assets/Gwent/cards/ — see docs/gwent-0a-specifikacio.md §5.
// To fix a card's data, edit the research JSON (or this script's override tables) and rerun.
import type { CardDef } from './types';

export const CARD_DEFS: CardDef[] = [
  {
    id: "monsters-arachas",
    name: "Arachas",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Ugly - nature's way of saying: Stay the fuck away.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/monsters-arachas-1.jpg", "/assets/gwent/cards/monsters-arachas-2.jpg", "/assets/gwent/cards/monsters-arachas-3.jpg"],
  },
  {
    id: "monsters-arachas-behemoth",
    name: "Arachas Behemoth",
    faction: "Monsters",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Like a cross between a crab, a spider... and a ploughin' mountain.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-arachas-behemoth-1.jpg"],
  },
  {
    id: "monsters-botchling",
    name: "Botchling",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Admit your mistakes and bury them proper - else they'll come back to haunt you.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-botchling-1.jpg"],
  },
  {
    id: "monsters-celaeno-harpy",
    name: "Celaeno Harpy",
    faction: "Monsters",
    kind: "Unit",
    row: null,
    basePower: 2,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Common harpies feed on carrion. Celaeno harpies... they feed on dreams.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-celaeno-harpy-1.jpg"],
  },
  {
    id: "monsters-cockatrice",
    name: "Cockatrice",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Born of an egg laid by a cockerel... if you believe such peasant drivel.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-cockatrice-1.jpg"],
  },
  {
    id: "monsters-crone-brewess",
    name: "Crone Brewess",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-crone-weavess", "monsters-crone-whispess"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"We'll cut you up, boy. A fine broth you will make.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-crone-brewess-1.jpg"],
  },
  {
    id: "monsters-crone-weavess",
    name: "Crone Weavess",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-crone-brewess", "monsters-crone-whispess"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I sense your pain. I see your fear...\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-crone-weavess-1.jpg"],
  },
  {
    id: "monsters-crone-whispess",
    name: "Crone Whispess",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-crone-brewess", "monsters-crone-weavess"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I'd be your best - and last.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-crone-whispess-1.jpg"],
  },
  {
    id: "monsters-draug",
    name: "Draug",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Some men cannot admit defeat. Some keep fighting from beyond the grave.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-draug-1.jpg"],
  },
  {
    id: "monsters-earth-elemental",
    name: "Earth Elemental",
    faction: "Monsters",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"How do you fight an earth elemental? You don't. You run. Fast as you can.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-earth-elemental-1.jpg"],
  },
  {
    id: "monsters-endrega",
    name: "Endrega",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The nest! Take out the nest, or the bastards'll just keep coming.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-endrega-1.jpg"],
  },
  {
    id: "monsters-fiend",
    name: "Fiend",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"A fiend looks a bit like a deer. An enormous, evil deer.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-fiend-1.jpg"],
  },
  {
    id: "monsters-fire-elemental",
    name: "Fire Elemental",
    faction: "Monsters",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Fire is so delightful.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-fire-elemental-1.jpg"],
  },
  {
    id: "monsters-foglet",
    name: "Foglet",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Fog creeps on little cat feet. Foglets creep over the bodies of their victims.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-foglet-1.jpg"],
  },
  {
    id: "monsters-forktail",
    name: "Forktail",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Fork tails... Bah! Fuckers' tails're more like cleavers.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-forktail-1.jpg"],
  },
  {
    id: "monsters-frightener",
    name: "Frightener",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"What have I done? The mage cried out, frightened of his own creation.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-frightener-1.jpg"],
  },
  {
    id: "monsters-gargoyle",
    name: "Gargoyle",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Ancient sculptors' nightmarish fantasies, brought to life by bored mages.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-gargoyle-1.jpg"],
  },
  {
    id: "monsters-ghoul",
    name: "Ghoul",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 1,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"If ghouls are part of the Circle of Life... then it's a damn vicious circle.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/monsters-ghoul-1.jpg", "/assets/gwent/cards/monsters-ghoul-2.jpg", "/assets/gwent/cards/monsters-ghoul-3.jpg"],
  },
  {
    id: "monsters-grave-hag",
    name: "Grave Hag",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Their long tongues're for slurping marrow - and whipping prey.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-grave-hag-1.jpg"],
  },
  {
    id: "monsters-griffin",
    name: "Griffin",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Griffins like to toy with their prey. Eat 'em alive, piece by piece.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-griffin-1.jpg"],
  },
  {
    id: "monsters-harpy",
    name: "Harpy",
    faction: "Monsters",
    kind: "Unit",
    row: null,
    basePower: 2,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"There are many species of harpy, and all are kleptomaniacs.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-harpy-1.jpg"],
  },
  {
    id: "monsters-ice-giant",
    name: "Ice Giant",
    faction: "Monsters",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Fled one time in my life. From the Ice Giant. And I'm not a bit ashamed.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-ice-giant-1.jpg"],
  },
  {
    id: "monsters-imlerith",
    name: "Imlerith",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Ladd nahw! Kill them! Litter the earth with their entrails!\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-imlerith-1.jpg"],
  },
  {
    id: "monsters-kayran",
    name: "Kayran",
    faction: "Monsters",
    kind: "Unit",
    row: null,
    basePower: 8,
    abilities: ["Hero", "Agile", "MoraleBoost"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Kill a kayran? Simple. Take your best sword... then sell it and hire a witcher.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-kayran-1.jpg"],
  },
  {
    id: "monsters-leshen",
    name: "Leshen",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"We never hunt in these woods. Not even if it means the whole village starves.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-leshen-1.jpg"],
  },
  {
    id: "monsters-nekker",
    name: "Nekker",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 2,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Damn things are almost cute, if you ignore the whole vicious killer aspect.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/monsters-nekker-1.jpg", "/assets/gwent/cards/monsters-nekker-2.jpg", "/assets/gwent/cards/monsters-nekker-3.jpg"],
  },
  {
    id: "monsters-plague-maiden",
    name: "Plague Maiden",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The sick rave about a boil-pocked woman surrounded by herds of rabid rats...\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-plague-maiden-1.jpg"],
  },
  {
    id: "monsters-toad",
    name: "Toad",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 7,
    abilities: [],
    mustersWithIds: [],
    rowScorch: { targetRow: "Ranged", threshold: 10 },
    weatherRow: null,
    specialText: null,
    cardText: "\"Big. Bad. Ugly. Squats in the sewers.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-toad-1.jpg"],
  },
  {
    id: "monsters-vampire-bruxa",
    name: "Vampire Bruxa",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-vampire-ekimmara", "monsters-vampire-fleder", "monsters-vampire-garkain", "monsters-vampire-katakan"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"A vile, bloodthirsty, man-eating hag. Kind of like my mother-in-law.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-vampire-bruxa-1.jpg"],
  },
  {
    id: "monsters-vampire-ekimmara",
    name: "Vampire Ekimmara",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-vampire-bruxa", "monsters-vampire-fleder", "monsters-vampire-garkain", "monsters-vampire-katakan"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Who would think overgrown bats would have a taste for gaudy jewelry?\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-vampire-ekimmara-1.jpg"],
  },
  {
    id: "monsters-vampire-fleder",
    name: "Vampire Fleder",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-vampire-bruxa", "monsters-vampire-ekimmara", "monsters-vampire-garkain", "monsters-vampire-katakan"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Higher vampires embrace their victims. Fleders rip them to shreds.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-vampire-fleder-1.jpg"],
  },
  {
    id: "monsters-vampire-garkain",
    name: "Vampire Garkain",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-vampire-bruxa", "monsters-vampire-ekimmara", "monsters-vampire-fleder", "monsters-vampire-katakan"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Blood-drinkers and corpse-eaters so foul, their very ugliness paralyses foes.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-vampire-garkain-1.jpg"],
  },
  {
    id: "monsters-vampire-katakan",
    name: "Vampire Katakan",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: ["Muster"],
    mustersWithIds: ["monsters-vampire-bruxa", "monsters-vampire-ekimmara", "monsters-vampire-fleder", "monsters-vampire-garkain"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Drinking the blood of the Continent since the Conjunction.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-vampire-katakan-1.jpg"],
  },
  {
    id: "monsters-werewolf",
    name: "Werewolf",
    faction: "Monsters",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Wolves aren't as bad as they say. Werewolves, though - they're worse.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-werewolf-1.jpg"],
  },
  {
    id: "monsters-wyvern",
    name: "Wyvern",
    faction: "Monsters",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Imagine a cross between a winged snake and a nightmare. Wyverns are worse.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/monsters-wyvern-1.jpg"],
  },
  {
    id: "neutral-biting-frost",
    name: "Biting Frost",
    faction: "Neutral",
    kind: "Weather",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: "Melee",
    specialText: null,
    cardText: "\"Best part about frost - bodies of the fallen don't rot so quickly.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-biting-frost-1.jpg"],
  },
  {
    id: "neutral-bovine-defense-force",
    name: "Bovine Defense Force",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 8,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Grrrrrr!\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-bovine-defense-force-1.jpg"],
  },
  {
    id: "neutral-cirilla-fiona-elen-riannon",
    name: "Cirilla Fiona Elen Riannon",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 15,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Know when fairy tales cease to be tales? When people start believing in them.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-cirilla-fiona-elen-riannon-1.jpg", "/assets/gwent/cards/neutral-cirilla-fiona-elen-riannon-2.jpg"],
  },
  {
    id: "neutral-clear-weather",
    name: "Clear Weather",
    faction: "Neutral",
    kind: "Weather",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: "AllRows",
    specialText: null,
    cardText: "\"The sun's shinin', Dromle! The sun's shinin'! Maybe there's hope left after all...\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-clear-weather-1.jpg"],
  },
  {
    id: "neutral-commander-s-horn",
    name: "Commander's Horn",
    faction: "Neutral",
    kind: "Horn",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Plus one to morale, minus three to hearing.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-commander-s-horn-1.jpg"],
  },
  {
    id: "neutral-cow",
    name: "Cow",
    faction: "Neutral",
    kind: "Unit",
    row: "Ranged",
    basePower: 0,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: "Ha bármilyen módon lekerül a tábláról (pl. Scorch), automatikusan megjelenik helyette a Bovine Defense Force (8 erejű Melee egység).",
    cardText: "\"Mooo!\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-cow-1.jpg"],
  },
  {
    id: "neutral-dandelion",
    name: "Dandelion",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: "Amíg a táblán van, a saját sorában lévő MINDEN kártya ereje duplázva marad, önmagát is beleértve (pontosan úgy, mint egy Kürt hatása — ha a soron már aktív egy valódi Kürt, a Dandelion hatása nem érvényesül, a kettő nem összegződik).",
    cardText: "\"Dandelion, you're a cynic, a lecher, a whoremonger, a liar - and my best friend.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-dandelion-1.jpg", "/assets/gwent/cards/neutral-dandelion-2.jpg"],
  },
  {
    id: "neutral-decoy",
    name: "Decoy",
    faction: "Neutral",
    kind: "Decoy",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"When you have run out of peasants, decoys also make decent arrow fodder.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-decoy-1.jpg"],
  },
  {
    id: "neutral-emiel-regis-rohellec-terzieff",
    name: "Emiel Regis Rohellec Terzieff",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Men, the polite ones, at least, would call me a monster. A blood-drinking freak.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-emiel-regis-rohellec-terzieff-1.jpg", "/assets/gwent/cards/neutral-emiel-regis-rohellec-terzieff-2.jpg"],
  },
  {
    id: "neutral-gaunter-o-dimm",
    name: "Gaunter O'Dimm",
    faction: "Neutral",
    kind: "Unit",
    row: "Siege",
    basePower: 2,
    abilities: ["Muster"],
    mustersWithIds: ["neutral-gaunter-o-dimm-darkness"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"He always grants exactly what you wish for. That's the problem.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-gaunter-o-dimm-1.jpg"],
  },
  {
    id: "neutral-gaunter-o-dimm-darkness",
    name: "Gaunter O'Dimm: Darkness",
    faction: "Neutral",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: ["Muster"],
    mustersWithIds: ["neutral-gaunter-o-dimm"],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Fear not the shadows, but the light.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-gaunter-o-dimm-darkness-1.jpg"],
  },
  {
    id: "neutral-geralt-of-rivia",
    name: "Geralt of Rivia",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 15,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"If that's what it takes to save the world, it's better to let that world die.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-geralt-of-rivia-1.jpg", "/assets/gwent/cards/neutral-geralt-of-rivia-2.jpg"],
  },
  {
    id: "neutral-impenetrable-fog",
    name: "Impenetrable Fog",
    faction: "Neutral",
    kind: "Weather",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: "Ranged",
    specialText: null,
    cardText: "A good commander's dream... a bad one's horror.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-impenetrable-fog-1.jpg"],
  },
  {
    id: "neutral-mysterious-elf",
    name: "Mysterious Elf",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 0,
    abilities: ["Hero", "Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"You humans have... unusual tastes.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-mysterious-elf-1.jpg", "/assets/gwent/cards/neutral-mysterious-elf-2.jpg"],
  },
  {
    id: "neutral-olgierd-von-everec",
    name: "Olgierd von Everec",
    faction: "Neutral",
    kind: "Unit",
    row: null,
    basePower: 6,
    abilities: ["Agile", "MoraleBoost"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"At least you now know I don't easily lose my head.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-olgierd-von-everec-1.jpg"],
  },
  {
    id: "neutral-scorch",
    name: "Scorch",
    faction: "Neutral",
    kind: "Scorch",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Pillars of flame turn the mightiest to ash. All others tremble in shock and awe.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-scorch-1.jpg"],
  },
  {
    id: "neutral-torrential-rain",
    name: "Torrential Rain",
    faction: "Neutral",
    kind: "Weather",
    row: null,
    basePower: null,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: "Siege",
    specialText: null,
    cardText: "\"Even the rain in this land smells like piss.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/neutral-torrential-rain-1.jpg"],
  },
  {
    id: "neutral-triss-merigold",
    name: "Triss Merigold",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 7,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I can take care of myself. Trust me\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-triss-merigold-1.jpg", "/assets/gwent/cards/neutral-triss-merigold-2.jpg"],
  },
  {
    id: "neutral-vesemir",
    name: "Vesemir",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"If you're to be hanged, ask for water. Anything can happen before they fetch it.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-vesemir-1.jpg", "/assets/gwent/cards/neutral-vesemir-2.jpg"],
  },
  {
    id: "neutral-villentretenmerth",
    name: "Villentretenmerth",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 7,
    abilities: [],
    mustersWithIds: [],
    rowScorch: { targetRow: "Melee", threshold: 10 },
    weatherRow: null,
    specialText: null,
    cardText: "\"Also calls himself Borkh Three Jackdaws... he's not the best at names.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-villentretenmerth-1.jpg", "/assets/gwent/cards/neutral-villentretenmerth-2.jpg"],
  },
  {
    id: "neutral-yennefer-of-vengerberg",
    name: "Yennefer of Vengerberg",
    faction: "Neutral",
    kind: "Unit",
    row: "Ranged",
    basePower: 7,
    abilities: ["Hero", "Medic"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Magic is Chaos, Art and Science. It is a curse, a blessing and a progression.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-yennefer-of-vengerberg-1.jpg", "/assets/gwent/cards/neutral-yennefer-of-vengerberg-2.jpg"],
  },
  {
    id: "neutral-zoltan-chivay",
    name: "Zoltan Chivay",
    faction: "Neutral",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Life without old mates and booze is like a woman without a rump.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/neutral-zoltan-chivay-1.jpg", "/assets/gwent/cards/neutral-zoltan-chivay-2.jpg"],
  },
  {
    id: "nilfgaard-albrich",
    name: "Albrich",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"A fireball? Of course. Whatever Your Imperial Majesty wishes.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-albrich-1.jpg"],
  },
  {
    id: "nilfgaard-assire-var-anahid",
    name: "Assire var Anahid",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Nilfgaardian mages do have a choice: servile submission, or the gallows.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-assire-var-anahid-1.jpg"],
  },
  {
    id: "nilfgaard-black-infantry-archer",
    name: "Black Infantry Archer",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I aim for the knee. Always\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/nilfgaard-black-infantry-archer-1.jpg", "/assets/gwent/cards/nilfgaard-black-infantry-archer-2.jpg"],
  },
  {
    id: "nilfgaard-cahir-mawr-dyffryn-aep-ceallach",
    name: "Cahir Mawr Dyffryn aep Ceallach",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"His eyes flashed under his winged helmet. Fire gleamed from his sword's blade.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-cahir-mawr-dyffryn-aep-ceallach-1.jpg"],
  },
  {
    id: "nilfgaard-cynthia",
    name: "Cynthia",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Cynthia's talents can be deadly. She needs a tight leash.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-cynthia-1.jpg"],
  },
  {
    id: "nilfgaard-etolian-auxiliary-archers",
    name: "Etolian Auxiliary Archers",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 1,
    abilities: ["Medic"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Double or nothing, aim for his cock.\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/nilfgaard-etolian-auxiliary-archers-1.jpg", "/assets/gwent/cards/nilfgaard-etolian-auxiliary-archers-2.jpg"],
  },
  {
    id: "nilfgaard-fringilla-vigo",
    name: "Fringilla Vigo",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Magic is the highest good. It transcends all borders and divisions.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-fringilla-vigo-1.jpg"],
  },
  {
    id: "nilfgaard-heavy-zerrikanian-fire-scorpion",
    name: "Heavy Zerrikanian Fire Scorpion",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Siege",
    basePower: 10,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Not the best for taking cities, but great for razing them to the ground.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-heavy-zerrikanian-fire-scorpion-1.jpg"],
  },
  {
    id: "nilfgaard-impera-brigade-guard",
    name: "Impera Brigade Guard",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 3,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The imperia Brigade never surrenders. Ever.\"",
    copies: 4,
    imagePaths: ["/assets/gwent/cards/nilfgaard-impera-brigade-guard-1.jpg", "/assets/gwent/cards/nilfgaard-impera-brigade-guard-2.jpg", "/assets/gwent/cards/nilfgaard-impera-brigade-guard-3.jpg", "/assets/gwent/cards/nilfgaard-impera-brigade-guard-4.jpg"],
  },
  {
    id: "nilfgaard-letho-of-gulet",
    name: "Letho of Gulet",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Witchers never die in their beds.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-letho-of-gulet-1.jpg"],
  },
  {
    id: "nilfgaard-menno-coehoorn",
    name: "Menno Coehoorn",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero", "Medic"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I'll take an attentive reconnaissance unit over a fine cavalry brigade any day.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-menno-coehoorn-1.jpg"],
  },
  {
    id: "nilfgaard-morteisen",
    name: "Morteisen",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 3,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"No Nordling pikemen or dwarven spearbearers can hope to best trained cavalry.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-morteisen-1.jpg"],
  },
  {
    id: "nilfgaard-morvran-voorhis",
    name: "Morvran Voorhis",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Siege",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Summer sun reflecting in the quiet waters of the Alba - that's Nilfgaard to me.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-morvran-voorhis-1.jpg"],
  },
  {
    id: "nilfgaard-nausicaa-cavalry-rider",
    name: "Nausicaa Cavalry Rider",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 2,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The Emperor will teach the North discipline.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/nilfgaard-nausicaa-cavalry-rider-1.jpg", "/assets/gwent/cards/nilfgaard-nausicaa-cavalry-rider-2.jpg", "/assets/gwent/cards/nilfgaard-nausicaa-cavalry-rider-3.jpg"],
  },
  {
    id: "nilfgaard-puttkammer",
    name: "Puttkammer",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 3,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Learned a lot at Braibant Military Academy. How to scrub potatoes, for instance.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-puttkammer-1.jpg"],
  },
  {
    id: "nilfgaard-rainfarn",
    name: "Rainfarn",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"You'll die as painfully as that pathetic traitor Windhalm did.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-rainfarn-1.jpg"],
  },
  {
    id: "nilfgaard-renuald-aep-matsen",
    name: "Renuald aep Matsen",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"They say the Impera fear nothing. Untrue. Renuald scares them shitless.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-renuald-aep-matsen-1.jpg"],
  },
  {
    id: "nilfgaard-rotten-mangonel",
    name: "Rotten Mangonel",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Siege",
    basePower: 3,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The rotten smell brings back childhood memories.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-rotten-mangonel-1.jpg"],
  },
  {
    id: "nilfgaard-shilard-fitz-oesterlen",
    name: "Shilard Fitz-Oesterlen",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 7,
    abilities: ["Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Warfare is mere sound and fury - diplomacy is what truly shapes history.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-shilard-fitz-oesterlen-1.jpg"],
  },
  {
    id: "nilfgaard-siege-engineer",
    name: "Siege Engineer",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Wielded correctly, a protractor can be a deadly weapon.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-siege-engineer-1.jpg"],
  },
  {
    id: "nilfgaard-siege-technician",
    name: "Siege Technician",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Siege",
    basePower: 0,
    abilities: ["Medic"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I never miss twice.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-siege-technician-1.jpg"],
  },
  {
    id: "nilfgaard-stefan-skellen",
    name: "Stefan Skellen",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 9,
    abilities: ["Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"My mark scars the face of our future empress. That is my proudest achievement.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-stefan-skellen-1.jpg"],
  },
  {
    id: "nilfgaard-sweers",
    name: "Sweers",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"And hands off the girl! Whatever we may be, we're not savages.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-sweers-1.jpg"],
  },
  {
    id: "nilfgaard-tibor-eggebracht",
    name: "Tibor Eggebracht",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Albaaaa! Forward!! Alba! Long live the Emperor!\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-tibor-eggebracht-1.jpg"],
  },
  {
    id: "nilfgaard-vanhemar",
    name: "Vanhemar",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"For a fire mage, he's not very... flamboyant.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-vanhemar-1.jpg"],
  },
  {
    id: "nilfgaard-vattier-de-rideaux",
    name: "Vattier de Rideaux",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"There's never been a problem a well-planned assassination couldn't solve.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-vattier-de-rideaux-1.jpg"],
  },
  {
    id: "nilfgaard-vreemde",
    name: "Vreemde",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Discipline is the Empire's greatest weapon\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-vreemde-1.jpg"],
  },
  {
    id: "nilfgaard-young-emissary",
    name: "Young Emissary",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"If I acquit myself well, perhaps next they'll post me somewhere civilized.\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/nilfgaard-young-emissary-1.jpg", "/assets/gwent/cards/nilfgaard-young-emissary-2.jpg"],
  },
  {
    id: "nilfgaard-zerrikanian-fire-scorpion",
    name: "Zerrikanian Fire Scorpion",
    faction: "Nilfgaard",
    kind: "Unit",
    row: "Siege",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The Zerrikanian desert used to be a lush garden. Then these came along.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/nilfgaard-zerrikanian-fire-scorpion-1.jpg"],
  },
  {
    id: "northern-realms-ballista",
    name: "Ballista",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Usually we give 'em female names.\" - \"Like Jenny?\" - \"More like Bertha.\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/northern-realms-ballista-1.jpg", "/assets/gwent/cards/northern-realms-ballista-2.jpg"],
  },
  {
    id: "northern-realms-blue-stripes-commando",
    name: "Blue Stripes Commando",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I'd anything for Temeria. Mostly, though, I kill for her.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/northern-realms-blue-stripes-commando-1.jpg", "/assets/gwent/cards/northern-realms-blue-stripes-commando-2.jpg", "/assets/gwent/cards/northern-realms-blue-stripes-commando-3.jpg"],
  },
  {
    id: "northern-realms-catapult",
    name: "Catapult",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 8,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The gods help those who have better catapults.\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/northern-realms-catapult-1.jpg", "/assets/gwent/cards/northern-realms-catapult-2.jpg"],
  },
  {
    id: "northern-realms-crinfrid-reavers-dragon-hunter",
    name: "Crinfrid Reavers Dragon Hunter",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 5,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Haven't had much luck with monsters of late, so we enlisted.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/northern-realms-crinfrid-reavers-dragon-hunter-1.jpg", "/assets/gwent/cards/northern-realms-crinfrid-reavers-dragon-hunter-2.jpg", "/assets/gwent/cards/northern-realms-crinfrid-reavers-dragon-hunter-3.jpg"],
  },
  {
    id: "northern-realms-dethmold",
    name: "Dethmold",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I once made a prisoner vomit his own entrails... Ah, good times...\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-dethmold-1.jpg"],
  },
  {
    id: "northern-realms-dun-banner-medic",
    name: "Dun Banner Medic",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 5,
    abilities: ["Medic"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Stitch red to red, white to white, and everything will be all right.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-dun-banner-medic-1.jpg"],
  },
  {
    id: "northern-realms-esterad-thyssen",
    name: "Esterad Thyssen",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Like all Thyssen men, he was tall, powerfully built and criminally handsome.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-esterad-thyssen-1.jpg"],
  },
  {
    id: "northern-realms-john-natalis",
    name: "John Natalis",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"That square should bear the names of my soldiers, of the dead. Not mine.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-john-natalis-1.jpg"],
  },
  {
    id: "northern-realms-kaedweni-siege-expert",
    name: "Kaedweni Siege Expert",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 1,
    abilities: ["MoraleBoost"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"You gotta recalibrate the arm by five degrees.\" - \"Do what by the what now?\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/northern-realms-kaedweni-siege-expert-1.jpg", "/assets/gwent/cards/northern-realms-kaedweni-siege-expert-2.jpg", "/assets/gwent/cards/northern-realms-kaedweni-siege-expert-3.jpg"],
  },
  {
    id: "northern-realms-keira-metz",
    name: "Keira Metz",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"If I'm to die today, I wish to look smashing for the occasion.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-keira-metz-1.jpg"],
  },
  {
    id: "northern-realms-philippa-eilhart",
    name: "Philippa Eilhart",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Soon the power of kings will wither, and the Lodge shall seize its rightful place.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-philippa-eilhart-1.jpg"],
  },
  {
    id: "northern-realms-poor-fucking-infantry",
    name: "Poor Fucking Infantry",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 1,
    abilities: ["TightBond"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"It's a war veteran! ...spare me a crown?\"",
    copies: 4,
    imagePaths: ["/assets/gwent/cards/northern-realms-poor-fucking-infantry-1.jpg", "/assets/gwent/cards/northern-realms-poor-fucking-infantry-2.jpg", "/assets/gwent/cards/northern-realms-poor-fucking-infantry-3.jpg"],
  },
  {
    id: "northern-realms-prince-stennis",
    name: "Prince Stennis",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: ["Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"He ploughin' wears golden armor. Golden. 'Course he's an arsehole.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-prince-stennis-1.jpg"],
  },
  {
    id: "northern-realms-redanian-foot-soldier",
    name: "Redanian Foot Soldier",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 1,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "I've bled for Redania! I've killed for Redania... Dammit, I've even raped for Redania!",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/northern-realms-redanian-foot-soldier-1.jpg", "/assets/gwent/cards/northern-realms-redanian-foot-soldier-2.jpg"],
  },
  {
    id: "northern-realms-sabrina-glevissig",
    name: "Sabrina Glevissig",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The Daughter of the Kaedweni Wilderness.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-sabrina-glevissig-1.jpg"],
  },
  {
    id: "northern-realms-sheldon-skaggs",
    name: "Sheldon Skaggs",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I was there, on the front lines! Right where the fightin' was the thickest!\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-sheldon-skaggs-1.jpg"],
  },
  {
    id: "northern-realms-siege-tower",
    name: "Siege Tower",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I love the clamor of siege towers in the morning. Sounds like victory.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-siege-tower-1.jpg", "/assets/gwent/cards/northern-realms-siege-tower-2.jpg"],
  },
  {
    id: "northern-realms-siegfried-of-denesle",
    name: "Siegfried of Denesle",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"We're on the same side, witcher. You'll realize this one day.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-siegfried-of-denesle-1.jpg"],
  },
  {
    id: "northern-realms-sigismund-dijkstra",
    name: "Sigismund Dijkstra",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 4,
    abilities: ["Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Gwent's like politics, just more honest.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-sigismund-dijkstra-1.jpg"],
  },
  {
    id: "northern-realms-sile-de-tansarville",
    name: "Síle de Tansarville",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Ranged",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The Lodge lacks humility. Our lust for power may yet be our undoing.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-sile-de-tansarville-1.jpg"],
  },
  {
    id: "northern-realms-thaler",
    name: "Thaler",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 1,
    abilities: ["Spy"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Fuck off! We aren't all ploughin' philanderers. Some of us have depth...\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-thaler-1.jpg"],
  },
  {
    id: "northern-realms-trebuchet",
    name: "Trebuchet",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Siege",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Castle won't batter itself down, now will it? Get them trebuchets rollin'!\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/northern-realms-trebuchet-1.jpg", "/assets/gwent/cards/northern-realms-trebuchet-2.jpg"],
  },
  {
    id: "northern-realms-vernon-roche",
    name: "Vernon Roche",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"A patriot... and a real son of a bitch.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-vernon-roche-1.jpg"],
  },
  {
    id: "northern-realms-ves",
    name: "Ves",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Better to live one day as a king than a whole life as a beggar.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-ves-1.jpg"],
  },
  {
    id: "northern-realms-yarpen-zigrin",
    name: "Yarpen Zigrin",
    faction: "NorthernRealms",
    kind: "Unit",
    row: "Melee",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The world belongs to whoever's best at crackin' skulls and impregnatin' lasses.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/northern-realms-yarpen-zigrin-1.jpg"],
  },
  {
    id: "scoiatael-barclay-els",
    name: "Barclay Els",
    faction: "Scoiatael",
    kind: "Unit",
    row: null,
    basePower: 6,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Our mead smells like piss, do it? Easy to fix - I'll break your fuckin' nose!\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-barclay-els-1.jpg"],
  },
  {
    id: "scoiatael-ciaran-aep-easnillien",
    name: "Ciaran aep Easnillien",
    faction: "Scoiatael",
    kind: "Unit",
    row: null,
    basePower: 3,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The path to freedom is paved in blood, not ink.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-ciaran-aep-easnillien-1.jpg"],
  },
  {
    id: "scoiatael-dennis-cranmer",
    name: "Dennis Cranmer",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Melee",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I know how to carry out orders, so you can shove you advice up your coal chute.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-dennis-cranmer-1.jpg"],
  },
  {
    id: "scoiatael-dol-blathanna-archer",
    name: "Dol Blathanna Archer",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Take another step, dh'oine. You'd look better with an arrow between your eyes.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-dol-blathanna-archer-1.jpg"],
  },
  {
    id: "scoiatael-dol-blathanna-scout",
    name: "Dol Blathanna Scout",
    faction: "Scoiatael",
    kind: "Unit",
    row: null,
    basePower: 6,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"They track like hounds, run like deer and kill like cold-hearted bastards.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/scoiatael-dol-blathanna-scout-1.jpg", "/assets/gwent/cards/scoiatael-dol-blathanna-scout-2.jpg", "/assets/gwent/cards/scoiatael-dol-blathanna-scout-3.jpg"],
  },
  {
    id: "scoiatael-dwarven-skirmisher",
    name: "Dwarven Skirmisher",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Melee",
    basePower: 3,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Worked a pickaxe all me life. Battleaxe won't be any trouble.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/scoiatael-dwarven-skirmisher-1.jpg", "/assets/gwent/cards/scoiatael-dwarven-skirmisher-2.jpg", "/assets/gwent/cards/scoiatael-dwarven-skirmisher-3.jpg"],
  },
  {
    id: "scoiatael-eithne",
    name: "Eithné",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"The dryad queen has eyes of molten silver, and a heart of cold-forged steel.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-eithne-1.jpg"],
  },
  {
    id: "scoiatael-elven-skirmisher",
    name: "Elven Skirmisher",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"No matter what you may have heard, elves don't take human scalps. Too much lice.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/scoiatael-elven-skirmisher-1.jpg", "/assets/gwent/cards/scoiatael-elven-skirmisher-2.jpg", "/assets/gwent/cards/scoiatael-elven-skirmisher-3.jpg"],
  },
  {
    id: "scoiatael-filavandrel-aen-fidhail",
    name: "Filavandrel aen Fidhail",
    faction: "Scoiatael",
    kind: "Unit",
    row: null,
    basePower: 6,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Though we are now few and scattered, our hearts burn brighter than ever.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-filavandrel-aen-fidhail-1.jpg"],
  },
  {
    id: "scoiatael-havekar-healer",
    name: "Havekar Healer",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 0,
    abilities: ["Medic"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Sure, I'll patch you up. Gonna cost you, though.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/scoiatael-havekar-healer-1.jpg", "/assets/gwent/cards/scoiatael-havekar-healer-2.jpg", "/assets/gwent/cards/scoiatael-havekar-healer-3.jpg"],
  },
  {
    id: "scoiatael-havekar-smuggler",
    name: "Havekar Smuggler",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: ["Muster"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I fight for whoever's paying the best. Or whoever's easiest to rob.\"",
    copies: 3,
    imagePaths: ["/assets/gwent/cards/scoiatael-havekar-smuggler-1.jpg", "/assets/gwent/cards/scoiatael-havekar-smuggler-2.jpg", "/assets/gwent/cards/scoiatael-havekar-smuggler-3.jpg"],
  },
  {
    id: "scoiatael-ida-emean-aep-sivney",
    name: "Ida Emean aep Sivney",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 6,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I am a sage. My power lies in possessing knowledge. Not sharing it.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-ida-emean-aep-sivney-1.jpg"],
  },
  {
    id: "scoiatael-iorveth",
    name: "Iorveth",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"King or beggar, what's the difference? One dh'oine less.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-iorveth-1.jpg"],
  },
  {
    id: "scoiatael-isengrim-faoiltiarna",
    name: "Isengrim Faoiltiarna",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Melee",
    basePower: 10,
    abilities: ["Hero", "MoraleBoost"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"It dawns on them once they notice my scar: a realization of imminent death.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-isengrim-faoiltiarna-1.jpg"],
  },
  {
    id: "scoiatael-mahakaman-defender",
    name: "Mahakaman Defender",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Melee",
    basePower: 5,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I'm telling ye, we're born fer battle - we slash straight at their knees!\"",
    copies: 5,
    imagePaths: ["/assets/gwent/cards/scoiatael-mahakaman-defender-1.jpg", "/assets/gwent/cards/scoiatael-mahakaman-defender-2.jpg", "/assets/gwent/cards/scoiatael-mahakaman-defender-3.jpg", "/assets/gwent/cards/scoiatael-mahakaman-defender-4.jpg", "/assets/gwent/cards/scoiatael-mahakaman-defender-5.jpg"],
  },
  {
    id: "scoiatael-milva",
    name: "Milva",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["MoraleBoost"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"With each arrow I loose, I think of my da. He'd be proud. I think.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-milva-1.jpg"],
  },
  {
    id: "scoiatael-riordain",
    name: "Riordain",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 1,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Stare into their eyes, feast on their terror. Then go in for the kill.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-riordain-1.jpg"],
  },
  {
    id: "scoiatael-saesenthessis",
    name: "Saesenthessis",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 10,
    abilities: ["Hero"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Beautiful, pure, fierce - the perfect icon for a rebellion.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-saesenthessis-1.jpg"],
  },
  {
    id: "scoiatael-schirru",
    name: "Schirrú",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Siege",
    basePower: 8,
    abilities: [],
    mustersWithIds: [],
    rowScorch: { targetRow: "Siege", threshold: 10 },
    weatherRow: null,
    specialText: null,
    cardText: "\"Time to look death in the face.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-schirru-1.jpg"],
  },
  {
    id: "scoiatael-toruviel",
    name: "Toruviel",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 2,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"I'd gladly kill you from up close, stare in your eyes... But you reek, human.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-toruviel-1.jpg"],
  },
  {
    id: "scoiatael-vrihedd-brigade-recruit",
    name: "Vrihedd Brigade Recruit",
    faction: "Scoiatael",
    kind: "Unit",
    row: "Ranged",
    basePower: 4,
    abilities: [],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Hatred burns brighter than any fire, and cuts deeper than any blade.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-vrihedd-brigade-recruit-1.jpg"],
  },
  {
    id: "scoiatael-vrihedd-brigade-veteran",
    name: "Vrihedd Brigade Veteran",
    faction: "Scoiatael",
    kind: "Unit",
    row: null,
    basePower: 5,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"Vrihedd? What's that mean?\" - \"Trouble.\"",
    copies: 2,
    imagePaths: ["/assets/gwent/cards/scoiatael-vrihedd-brigade-veteran-1.jpg", "/assets/gwent/cards/scoiatael-vrihedd-brigade-veteran-2.jpg"],
  },
  {
    id: "scoiatael-yaevinn",
    name: "Yaevinn",
    faction: "Scoiatael",
    kind: "Unit",
    row: null,
    basePower: 6,
    abilities: ["Agile"],
    mustersWithIds: [],
    rowScorch: null,
    weatherRow: null,
    specialText: null,
    cardText: "\"We are the drops of rain that together make a ferocious storm.\"",
    copies: 1,
    imagePaths: ["/assets/gwent/cards/scoiatael-yaevinn-1.jpg"],
  },
];

export function getCardDef(id: string): CardDef {
  const def = CARD_DEFS.find((c) => c.id === id);
  if (!def) throw new Error(`Unknown Gwent card: ${id}`);
  return def;
}
