// GENERATED FILE — do not hand-edit. Produced by `node scripts/build-gwent-assets.mjs`
// from temp/gwent-card-data.json + assets/Gwent/cards/ — see docs/gwent-0a-specifikacio.md §4.5.
import type { LeaderDef } from './types';

export const LEADER_DEFS: LeaderDef[] = [
  {
    id: "monsters-eredin-breacc-glas-the-treacherous",
    name: "Eredin Breacc Glas The Treacherous",
    faction: "Monsters",
    abilityId: "monsters-eredin-breacc-glas-the-treacherous",
    abilityDescription: "Megduplázza minden táblán lévő Kém (Spy) kártya erejét — mindkét játékos kémjeire vonatkozik.",
    cardText: "\"I'm enjoying this. You are my toy.\"",
    imagePaths: ["/assets/gwent/leaders/monsters-eredin-breacc-glas-the-treacherous-1.jpg"],
  },
  {
    id: "monsters-eredin-bringer-of-death",
    name: "Eredin Bringer of Death",
    faction: "Monsters",
    abilityId: "monsters-eredin-bringer-of-death",
    abilityDescription: "Dobj el 2 lapot a kezedből, majd húzz 1, általad választott lapot a paklidból.",
    cardText: "\"It is unavoidable.\"",
    imagePaths: ["/assets/gwent/leaders/monsters-eredin-bringer-of-death-1.jpg"],
  },
  {
    id: "monsters-eredin-commander-of-the-red-riders",
    name: "Eredin Commander of the Red Riders",
    faction: "Monsters",
    abilityId: "monsters-eredin-commander-of-the-red-riders",
    abilityDescription: "Válassz egy tetszőleges időjárás-kártyát a paklidból, és játszd le azonnal.",
    cardText: "\"Go on. Show me your spins, piruettes and feints. I want to watch.\"",
    imagePaths: ["/assets/gwent/leaders/monsters-eredin-commander-of-the-red-riders-1.jpg"],
  },
  {
    id: "monsters-eredin-destroyer-of-worlds",
    name: "Eredin Destroyer of Worlds",
    faction: "Monsters",
    abilityId: "monsters-eredin-destroyer-of-worlds",
    abilityDescription: "Végy vissza egy lapot a dobott lapjaid közül a kezedbe.",
    cardText: "\"I've long awaited this...\"",
    imagePaths: ["/assets/gwent/leaders/monsters-eredin-destroyer-of-worlds-1.jpg"],
  },
  {
    id: "monsters-eredin-king-of-the-wild-hunt",
    name: "Eredin King of the Wild Hunt",
    faction: "Monsters",
    abilityId: "monsters-eredin-king-of-the-wild-hunt",
    abilityDescription: "Megduplázza minden közelharci (Melee) egységed erejét ezen a körben, mint egy Kürt-lap lejátszása.",
    cardText: "\"Have some dignity. You know how this will end.\"",
    imagePaths: ["/assets/gwent/leaders/monsters-eredin-king-of-the-wild-hunt-1.jpg"],
  },
  {
    id: "nilfgaard-emhyr-var-emreis-emperor-of-nilfgaard",
    name: "Emhyr var Emreis: Emperor of Nilfgaard",
    faction: "Nilfgaard",
    abilityId: "nilfgaard-emhyr-var-emreis-emperor-of-nilfgaard",
    abilityDescription: "Megnézhetsz 3 véletlenszerű lapot az ellenfél kezéből.",
    cardText: "\"Your motives do not interest me. Only results.\"",
    imagePaths: ["/assets/gwent/leaders/nilfgaard-emhyr-var-emreis-emperor-of-nilfgaard-1.jpg"],
  },
  {
    id: "nilfgaard-emhyr-var-emreis-his-imperial-majesty",
    name: "Emhyr var Emreis: His Imperial Majesty",
    faction: "Nilfgaard",
    abilityId: "nilfgaard-emhyr-var-emreis-his-imperial-majesty",
    abilityDescription: "Válassz egy Felhőszakadás kártyát a paklidból, és játszd le azonnal.",
    cardText: "\"The skies wept when my Pavetta died. They will not weep for me.\"",
    imagePaths: ["/assets/gwent/leaders/nilfgaard-emhyr-var-emreis-his-imperial-majesty-1.jpg"],
  },
  {
    id: "nilfgaard-emhyr-var-emreis-invader-of-the-north",
    name: "Emhyr var Emreis: Invader of the North",
    faction: "Nilfgaard",
    abilityId: "nilfgaard-emhyr-var-emreis-invader-of-the-north",
    abilityDescription: "Minden, egységet a táblára visszahozó képesség egy véletlenszerűen kiválasztott egységet hoz vissza — mindkét játékosra érvényes.",
    cardText: "\"Emperors command multitudes, yet cannot control two things: their time and their hearts.\"",
    imagePaths: ["/assets/gwent/leaders/nilfgaard-emhyr-var-emreis-invader-of-the-north-1.jpg"],
  },
  {
    id: "nilfgaard-emhyr-var-emreis-the-relentless",
    name: "Emhyr var Emreis: The Relentless",
    faction: "Nilfgaard",
    abilityId: "nilfgaard-emhyr-var-emreis-the-relentless",
    abilityDescription: "Húzz egy lapot az ellenfél dobott lapjai közül.",
    cardText: "\"They do not call me the Patient. Take care they do not call you the Headless.\"",
    imagePaths: ["/assets/gwent/leaders/nilfgaard-emhyr-var-emreis-the-relentless-1.jpg"],
  },
  {
    id: "nilfgaard-emhyr-var-emreis-the-white-flame",
    name: "Emhyr var Emreis: The White Flame",
    faction: "Nilfgaard",
    abilityId: "nilfgaard-emhyr-var-emreis-the-white-flame",
    abilityDescription: "Semlegesíti az ellenfél vezér-képességét.",
    cardText: "\"A sword is but one of many tools at a ruler's disposal.\"",
    imagePaths: ["/assets/gwent/leaders/nilfgaard-emhyr-var-emreis-the-white-flame-1.jpg"],
  },
  {
    id: "northern-realms-foltest-king-of-temeria",
    name: "Foltest, King of Temeria",
    faction: "NorthernRealms",
    abilityId: "northern-realms-foltest-king-of-temeria",
    abilityDescription: "Válassz egy Áthatolhatatlan köd kártyát a paklidból, és játszd le azonnal.",
    cardText: "\"It is natural and beautiful that a man should love his sister.\"",
    imagePaths: ["/assets/gwent/leaders/northern-realms-foltest-king-of-temeria-1.jpg"],
  },
  {
    id: "northern-realms-foltest-lord-commander-of-the-north",
    name: "Foltest, Lord Commander of the North",
    faction: "NorthernRealms",
    abilityId: "northern-realms-foltest-lord-commander-of-the-north",
    abilityDescription: "Töröl minden aktív időjárás-hatást, mindkét oldalon.",
    cardText: "\"Sod advisors and their schemes. I place my trust in my soldiers' blades.\"",
    imagePaths: ["/assets/gwent/leaders/northern-realms-foltest-lord-commander-of-the-north-1.jpg"],
  },
  {
    id: "northern-realms-foltest-son-of-medell",
    name: "Foltest, Son of Medell",
    faction: "NorthernRealms",
    abilityId: "northern-realms-foltest-son-of-medell",
    abilityDescription: "Elpusztítja az ellenfél legerősebb távolsági (Ranged) egységét/egységeit, ha az adott sor össz-ereje eléri a 10-et, és lapfelhasználás nélkül Kürt-hatást aktivál a saját távolsági sorodon.",
    cardText: "\"Dammit, I rule this land and I refuse to creep around its corners.\"",
    imagePaths: ["/assets/gwent/leaders/northern-realms-foltest-son-of-medell-1.jpg"],
  },
  {
    id: "northern-realms-foltest-the-siegemaster",
    name: "Foltest, The Siegemaster",
    faction: "NorthernRealms",
    abilityId: "northern-realms-foltest-the-siegemaster",
    abilityDescription: "Megduplázza minden ostrom (Siege) egységed erejét ezen a körben, mint egy Kürt-lap lejátszása.",
    cardText: "\"A well-aimed ballista razes not just the enemy's walls, but his morale as well.\"",
    imagePaths: ["/assets/gwent/leaders/northern-realms-foltest-the-siegemaster-1.jpg"],
  },
  {
    id: "northern-realms-foltest-the-steel-forged",
    name: "Foltest, The Steel-Forged",
    faction: "NorthernRealms",
    abilityId: "northern-realms-foltest-the-steel-forged",
    abilityDescription: "Elpusztítja az ellenfél legerősebb ostrom (Siege) egységét/egységeit, ha az adott sor össz-ereje eléri a 10-et.",
    cardText: "\"A beautiful day for battle.\"",
    imagePaths: ["/assets/gwent/leaders/northern-realms-foltest-the-steel-forged-1.jpg"],
  },
  {
    id: "scoiatael-francesca-findabair-daisy-of-the-valley",
    name: "Francesca Findabair: Daisy of the Valley",
    faction: "Scoiatael",
    abilityId: "scoiatael-francesca-findabair-daisy-of-the-valley",
    abilityDescription: "A parti elején húzz egy plusz lapot.",
    cardText: "\"Do not let my beauty distract your aim.\"",
    imagePaths: ["/assets/gwent/leaders/scoiatael-francesca-findabair-daisy-of-the-valley-1.jpg"],
  },
  {
    id: "scoiatael-francesca-findabair-hope-of-the-aen-seidhe",
    name: "Francesca Findabair: Hope of the Aen Seidhe",
    faction: "Scoiatael",
    abilityId: "scoiatael-francesca-findabair-hope-of-the-aen-seidhe",
    abilityDescription: "Minden Fürge (Agile) egységedet automatikusan abba az érvényes sorba helyezi, ahol a legtöbbet ér.",
    cardText: "\"Daede sian caente, Aen Seidhe en'allane ael coeden...\"",
    imagePaths: ["/assets/gwent/leaders/scoiatael-francesca-findabair-hope-of-the-aen-seidhe-1.jpg"],
  },
  {
    id: "scoiatael-francesca-findabair-pureblood-elf",
    name: "Francesca Findabair: Pureblood Elf",
    faction: "Scoiatael",
    abilityId: "scoiatael-francesca-findabair-pureblood-elf",
    abilityDescription: "Válassz egy Csípős fagy kártyát a paklidból, és játszd le azonnal.",
    cardText: "\"To live in peace, we first must kill. This is human oppression's cruel finale.\"",
    imagePaths: ["/assets/gwent/leaders/scoiatael-francesca-findabair-pureblood-elf-1.jpg"],
  },
  {
    id: "scoiatael-francesca-findabair-queen-of-dol-blathanna",
    name: "Francesca Findabair: Queen of Dol Blathanna",
    faction: "Scoiatael",
    abilityId: "scoiatael-francesca-findabair-queen-of-dol-blathanna",
    abilityDescription: "Elpusztítja az ellenfél legerősebb közelharci (Melee) egységét/egységeit, ha az adott sor össz-ereje eléri a 10-et.",
    cardText: "\"Ash shall fertilize the soil. By spring the valley shall bloom once more.\"",
    imagePaths: ["/assets/gwent/leaders/scoiatael-francesca-findabair-queen-of-dol-blathanna-1.jpg"],
  },
  {
    id: "scoiatael-francesca-findabair-the-beautiful",
    name: "Francesca Findabair: The Beautiful",
    faction: "Scoiatael",
    abilityId: "scoiatael-francesca-findabair-the-beautiful",
    abilityDescription: "Megduplázza minden távolsági (Ranged) egységed erejét ezen a körben, mint egy Kürt-lap lejátszása.",
    cardText: "\"The Elder Race have forgotten more than humans can ever hope to know.\"",
    imagePaths: ["/assets/gwent/leaders/scoiatael-francesca-findabair-the-beautiful-1.jpg"],
  },
];

export function getLeaderDef(id: string): LeaderDef {
  const def = LEADER_DEFS.find((l) => l.id === id);
  if (!def) throw new Error(`Unknown Gwent leader: ${id}`);
  return def;
}
